(function(){
function addStyles(){if(document.getElementById('sccyberPikPopStyles'))return;var s=document.createElement('style');s.id='sccyberPikPopStyles';s.textContent='.pik-pop-zone{position:fixed;inset:0;pointer-events:none;z-index:4;overflow:hidden}.pik-pop{position:absolute;width:52px;height:52px;opacity:1;animation-duration:1.2s;animation-timing-function:ease-out;animation-fill-mode:forwards;filter:drop-shadow(0 0 12px rgba(169,76,255,.45))}.pik-pop.left{animation-name:pikLeft}.pik-pop.right{animation-name:pikRight}.pik-pop.bottom{animation-name:pikBottom}.pik-pop.top{animation-name:pikTop}.pik-body{position:absolute;left:10px;top:8px;width:32px;height:32px;background:#fff;border-radius:10px;box-shadow:0 0 0 4px #090216,0 0 0 6px #a94cff,0 0 16px rgba(255,255,255,.4)}.pik-body:after{content:"";position:absolute;left:11px;top:20px;width:10px;height:4px;background:#a94cff;border-radius:0 0 8px 8px}.pik-arm{position:absolute;width:10px;height:5px;background:#fff;top:24px;box-shadow:0 0 0 2px #090216}.pik-arm.l{left:0}.pik-arm.r{right:0}.pik-leg{position:absolute;width:7px;height:9px;background:#fff;bottom:1px;box-shadow:0 0 0 2px #090216}.pik-leg.l{left:16px}.pik-leg.r{right:16px}@keyframes pikLeft{0%{transform:translateX(-70px)}20%{transform:translateX(0)}75%{transform:translateX(0)}100%{transform:translateX(-70px)}}@keyframes pikRight{0%{transform:translateX(70px)}20%{transform:translateX(0)}75%{transform:translateX(0)}100%{transform:translateX(70px)}}@keyframes pikBottom{0%{transform:translateY(70px)}20%{transform:translateY(0)}75%{transform:translateY(0)}100%{transform:translateY(70px)}}@keyframes pikTop{0%{transform:translateY(-70px)}20%{transform:translateY(0)}75%{transform:translateY(0)}100%{transform:translateY(-70px)}}';document.head.appendChild(s)}
function zone(){var z=document.getElementById('pikPopZone');if(z)return z;z=document.createElement('div');z.id='pikPopZone';z.className='pik-pop-zone';document.body.appendChild(z);return z}
function visible(){var l=document.getElementById('sccyberLanding');return !!(l&&!l.classList.contains('hidden'))}
function pik(d){var p=document.createElement('div');p.className='pik-pop '+d;p.innerHTML='<div class="pik-body"></div><div class="pik-arm l"></div><div class="pik-arm r"></div><div class="pik-leg l"></div><div class="pik-leg r"></div>';return p}
function pop(){if(!visible())return;var spots=[['-20px','22%','left'],['calc(100% - 32px)','32%','right'],['-20px','70%','left'],['calc(100% - 32px)','68%','right'],['12%','calc(100% - 32px)','bottom'],['82%','calc(100% - 32px)','bottom'],['24%','-20px','top']];var a=spots[Math.floor(Math.random()*spots.length)],p=pik(a[2]);p.style.left=a[0];p.style.top=a[1];zone().appendChild(p);setTimeout(function(){if(p.parentNode)p.parentNode.removeChild(p)},1300)}
function loop(){pop();setTimeout(loop,2600+Math.floor(Math.random()*1600))}
function start(){addStyles();zone();setTimeout(loop,800)}
window.addEventListener('load',start);if(document.readyState==='interactive'||document.readyState==='complete')setTimeout(start,150);
})();