const games=[{key:"breach-lockdown",name:"Breach Lockdown",tier:"Easy",focus:"Cyber awareness",premium:false},{key:"brute-force-lockdown",name:"Brute Force Lockdown",tier:"Advanced",focus:"Incident response",premium:true},{key:"phishing-frenzy",name:"Phishing Frenzy",tier:"Intermediate",focus:"Phishing detection",premium:true}];
const storageKey="sccyberPortalProfile";
const PASS_MARK=80;
let currentGameKey=null;
let supabaseClient=null;
let adminProfiles=[];
let adminAttempts=[];

const authView=document.getElementById("authView"),usernameInput=document.getElementById("usernameInput"),passwordInput=document.getElementById("passwordInput"),credentialLoginBtn=document.getElementById("credentialLoginBtn"),demoModeBtn=document.getElementById("demoModeBtn"),authMessage=document.getElementById("authMessage");
const loginPanel=document.getElementById("loginPanel"),learnerPanel=document.getElementById("learnerPanel"),firstNameInput=document.getElementById("firstName"),surnameInput=document.getElementById("surname"),departmentRoleInput=document.getElementById("departmentRole"),loginBtn=document.getElementById("loginBtn"),learnerDisplay=document.getElementById("learnerDisplay"),departmentDisplay=document.getElementById("departmentDisplay"),logoutBtn=document.getElementById("logoutBtn");
const overallScore=document.getElementById("overallScore"),gamesCompleted=document.getElementById("gamesCompleted"),trainingStatus=document.getElementById("trainingStatus"),reportBadge=document.getElementById("reportBadge"),reportProgress=document.getElementById("reportProgress"),reportAttempts=document.getElementById("reportAttempts"),reportOutput=document.getElementById("reportOutput");
const dashboardView=document.getElementById("dashboardView"),reportView=document.getElementById("reportView"),viewReportBtn=document.getElementById("viewReportBtn"),reportBackBtn=document.getElementById("reportBackBtn"),gameView=document.getElementById("gameView"),gameFrame=document.getElementById("gameFrame"),activeGameTitle=document.getElementById("activeGameTitle"),backBtn=document.getElementById("backBtn");
const adminBtn=document.getElementById("adminBtn"),adminView=document.getElementById("adminView"),adminBackBtn=document.getElementById("adminBackBtn"),refreshAdminBtn=document.getElementById("refreshAdminBtn"),adminCompanyCount=document.getElementById("adminCompanyCount"),adminLicenceCount=document.getElementById("adminLicenceCount"),adminLearnerCount=document.getElementById("adminLearnerCount"),adminOutput=document.getElementById("adminOutput"),billingOutput=document.getElementById("billingOutput"),adminLearnerOutput=document.getElementById("adminLearnerOutput"),adminSelectedReport=document.getElementById("adminSelectedReport");

function initSupabase(){const url=window.SCCYBER_SUPABASE_URL,key=window.SCCYBER_SUPABASE_ANON_KEY;if(!url||!key||url.includes("PASTE_")||key.includes("PASTE_")){authMessage.textContent="Supabase not connected yet. Use Demo Mode for local testing.";return;}supabaseClient=window.supabase.createClient(url,key);authMessage.textContent="Supabase ready. Enter learner credentials.";}
function usernameToEmail(username){const clean=username.trim().toLowerCase();return clean.includes("@")?clean:`${clean}@sccyber.training`;}
function showDashboard(){authView.classList.add("hidden");dashboardView.classList.remove("hidden");reportView.classList.add("hidden");gameView.classList.add("hidden");adminView.classList.add("hidden");updateDashboard();}
async function credentialLogin(){const username=usernameInput.value.trim(),password=passwordInput.value;if(!username||!password){authMessage.textContent="Enter username and password.";return;}if(!supabaseClient){authMessage.textContent="Supabase is not connected yet.";return;}authMessage.textContent="Checking credentials...";const {data,error}=await supabaseClient.auth.signInWithPassword({email:usernameToEmail(username),password});if(error){authMessage.textContent="Login failed. Check username and password.";return;}const user=data.user;const {data:profileData}=await supabaseClient.from("profiles").select("first_name,surname,department_role,username,is_admin,premium_enabled").eq("id",user.id).single();let profile;if(profileData){profile=createProfile(profileData.first_name,profileData.surname,profileData.department_role);profile.username=profileData.username||username;profile.isAdmin=!!profileData.is_admin;profile.premiumEnabled=!!profileData.premium_enabled;}else{profile=createProfile(username,"Learner","Unassigned");profile.username=username;profile.isAdmin=false;profile.premiumEnabled=false;}profile.supabaseUserId=user.id;profile.mode="live";saveProfile(profile);showDashboard();}
function demoMode(){const profile=createProfile("Demo","Learner","Demo");profile.mode="demo";profile.premiumEnabled=false;saveProfile(profile);showDashboard();}
async function logout(){localStorage.removeItem(storageKey);try{if(supabaseClient)await supabaseClient.auth.signOut();}catch(e){}usernameInput.value="";passwordInput.value="";dashboardView.classList.add("hidden");reportView.classList.add("hidden");gameView.classList.add("hidden");adminView.classList.add("hidden");authView.classList.remove("hidden");authMessage.textContent=supabaseClient?"Logged out. Enter learner credentials.":"Logged out. Supabase not connected.";window.scrollTo(0,0);}
function loadProfile(){const p=JSON.parse(localStorage.getItem(storageKey)||"null");if(p&&!p.attempts)p.attempts=[];return p;}
function saveProfile(p){if(!p.attempts)p.attempts=[];localStorage.setItem(storageKey,JSON.stringify(p));}
function validProfile(p){return !!(p&&p.firstName&&p.firstName.trim()&&p.surname&&p.surname.trim()&&p.departmentRole&&p.departmentRole.trim());}
function createProfile(firstName,surname,departmentRole){return{firstName:firstName.trim(),surname:surname.trim(),departmentRole:departmentRole.trim(),name:`${firstName.trim()} ${surname.trim()}`,scores:{},attempts:[],createdAt:new Date().toISOString(),isAdmin:false,premiumEnabled:false,mode:"local"};}
function hasPremiumAccess(){const profile=loadProfile();return !!(profile&&profile.premiumEnabled&&profile.mode!=="demo");}
function attemptsFor(p,gameKey){return(p.attempts||[]).filter(a=>a.game===gameKey);}
function bestScore(attempts){return attempts.length?Math.max(...attempts.map(a=>Number(a.score||0))):0;}
function attemptAccuracy(a){if(a.accuracy!==null&&a.accuracy!==undefined&&!Number.isNaN(Number(a.accuracy)))return Number(a.accuracy);if(a.answered&&a.correct!==null&&a.correct!==undefined)return Math.round((Number(a.correct)/Number(a.answered))*100);return 0;}
function bestAccuracy(attempts){return attempts.length?Math.max(...attempts.map(attemptAccuracy)):0;}
function latestAccuracy(attempts){return attempts.length?attemptAccuracy(attempts[attempts.length-1]):0;}
function averageAccuracy(attempts){return attempts.length?Math.round(attempts.reduce((s,a)=>s+attemptAccuracy(a),0)/attempts.length):0;}
function trainingGrade(avg,completed){if(completed<games.length)return"IN PROGRESS";return avg>=PASS_MARK?"PASS":"FAIL";}
async function saveAttemptToSupabase(attempt){const profile=loadProfile();if(!supabaseClient||!profile||!profile.supabaseUserId||profile.mode==="demo")return;await supabaseClient.from("attempts").insert({user_id:profile.supabaseUserId,game:attempt.game,score:attempt.score,accuracy:attempt.accuracy,correct_count:attempt.correct,wrong_count:attempt.wrong,answered:attempt.answered,duration_seconds:attempt.durationSeconds,passed:attempt.passed,created_at:attempt.createdAt});}
function addAttemptPayload(data){let profile=loadProfile();if(!validProfile(profile))return;const game=data.game||currentGameKey,score=Number(data.score||0);if(!game)return;const attempt={firstName:profile.firstName,surname:profile.surname,learnerName:profile.name,departmentRole:profile.departmentRole,game,score,source:data.source||"game",totalQuestions:data.totalQuestions||null,correct:data.correct||null,wrong:data.wrong||null,answered:data.answered||null,accuracy:data.accuracy||null,durationSeconds:data.durationSeconds||null,completed:data.completed===false?false:true,passed:data.passed||false,role:data.role||null,threatsStopped:data.threatsStopped||null,biggestWeakness:data.biggestWeakness||null,createdAt:data.createdAt||new Date().toISOString()};const dupe=profile.attempts.some(a=>a.game===attempt.game&&a.score===attempt.score&&a.answered===attempt.answered&&Math.abs(new Date(a.createdAt).getTime()-new Date(attempt.createdAt).getTime())<1500);if(dupe)return;profile.attempts.push(attempt);profile.scores[game]=bestScore(attemptsFor(profile,game));saveProfile(profile);saveAttemptToSupabase(attempt);updateDashboard();}
function calculateSummary(profile){const completedGames=games.filter(g=>attemptsFor(profile,g.key).length>0),completed=completedGames.length,bestAccuracies=completedGames.map(g=>bestAccuracy(attemptsFor(profile,g.key))),avg=completed?Math.round(bestAccuracies.reduce((a,b)=>a+b,0)/completed):0;return{completed,avg,totalAttempts:(profile.attempts||[]).length,status:completed?trainingGrade(avg,completed):"START TRAINING"};}
function updateReport(profile,summary){if(!validProfile(profile)){reportBadge.textContent="AWAITING PROFILE";reportProgress.textContent=`0 / ${games.length}`;reportAttempts.textContent="0";reportOutput.textContent="Enter learner details to start generating report data.";return;}reportProgress.textContent=`${summary.completed} / ${games.length}`;reportAttempts.textContent=summary.totalAttempts;reportBadge.textContent=summary.status;if(summary.totalAttempts===0){reportOutput.innerHTML="Complete at least one module to generate report data.";return;}const lines=games.map(g=>{const attempts=attemptsFor(profile,g.key);if(!attempts.length)return `<div class="report-line"><strong>${g.name}</strong><span>${g.tier}</span><span>${g.premium&&!hasPremiumAccess()?"Premium locked":"Not started"}</span><span>Attempts: 0</span></div>`;return `<div class="report-line"><strong>${g.name}</strong><span>${g.tier}</span><span>Best ${bestAccuracy(attempts)}% | Latest ${latestAccuracy(attempts)}% | Avg ${averageAccuracy(attempts)}%</span><span>Attempts: ${attempts.length}</span></div>`;}).join("");const missingGames=games.filter(g=>!attemptsFor(profile,g.key).length&&!g.premium).map(g=>g.name);let recommendation="Keep completing available modules.";if(missingGames.length)recommendation=`Next: complete ${missingGames[0]}.`;if(summary.completed===games.length&&summary.avg>=PASS_MARK)recommendation="Passed. Training standard met.";if(summary.completed===games.length&&summary.avg<PASS_MARK)recommendation="Retake the lowest scoring module. Overall average must reach 80%.";reportOutput.innerHTML=`<div class="report-section"><div class="report-section-title">Learner</div><p>${profile.name} · ${profile.departmentRole}</p></div><div class="report-section"><div class="report-section-title">Module Breakdown</div>${lines}</div><div class="report-section"><div class="report-section-title">Recommendation</div><p>${recommendation}</p></div>`;}
function updatePremiumButtons(){const premium=hasPremiumAccess();document.querySelectorAll(".game-card[data-premium='true']").forEach(card=>{const btn=card.querySelector(".play-btn");const score=card.querySelector(".game-score");if(premium){btn.textContent="Play";score.textContent=score.textContent==="Premium access required"?"No score yet":score.textContent;}else{btn.textContent="Upgrade to Play";score.textContent="Premium access required";}});}
function updateDashboard(){const profile=loadProfile();if(!validProfile(profile)){loginPanel.classList.remove("hidden");learnerPanel.classList.add("hidden");adminBtn.classList.add("hidden");overallScore.textContent="--";gamesCompleted.textContent=`0 / ${games.length}`;trainingStatus.textContent="ENTER PROFILE";games.forEach(g=>{const el=document.getElementById(`score-${g.key}`);if(el)el.textContent=g.premium?"Premium access required":"Profile required";});updatePremiumButtons();updateReport(profile,{completed:0,avg:0,totalAttempts:0,status:"ENTER PROFILE"});return;}loginPanel.classList.add("hidden");learnerPanel.classList.remove("hidden");learnerDisplay.textContent=profile.name;departmentDisplay.textContent=profile.departmentRole;profile.isAdmin?adminBtn.classList.remove("hidden"):adminBtn.classList.add("hidden");const summary=calculateSummary(profile);overallScore.textContent=summary.completed?`${summary.avg}%`:"--";gamesCompleted.textContent=`${summary.completed} / ${games.length}`;trainingStatus.textContent=summary.completed?summary.status:"START TRAINING";games.forEach(g=>{const el=document.getElementById(`score-${g.key}`),attempts=attemptsFor(profile,g.key);if(!el)return;if(g.premium&&!hasPremiumAccess()){el.textContent="Premium access required";return;}if(!attempts.length){el.textContent="No attempts yet";return;}el.innerHTML=`Best: ${bestAccuracy(attempts)}%<br>Latest: ${latestAccuracy(attempts)}%<br>Attempts: ${attempts.length}<br>Average: ${averageAccuracy(attempts)}%`;});updatePremiumButtons();updateReport(profile,summary);}
function remoteAccuracy(a){if(a.accuracy!==null&&a.accuracy!==undefined&&!Number.isNaN(Number(a.accuracy)))return Number(a.accuracy);if(a.answered&&a.correct_count!==null&&a.correct_count!==undefined)return Math.round((Number(a.correct_count)/Number(a.answered))*100);return 0;}
function buildRemoteSummary(attempts){const completedGames=games.filter(g=>attempts.some(a=>a.game===g.key));const completed=completedGames.length;const bests=completedGames.map(g=>Math.max(...attempts.filter(a=>a.game===g.key).map(remoteAccuracy)));const avg=completed?Math.round(bests.reduce((a,b)=>a+b,0)/completed):0;return{completed,avg,status:completed<games.length?"IN PROGRESS":avg>=PASS_MARK?"PASS":"FAIL",totalAttempts:attempts.length};}
function renderRemoteLearnerReport(profile,attempts){const summary=buildRemoteSummary(attempts);const name=`${profile.first_name||""} ${profile.surname||""}`.trim()||profile.username||"Learner";const rows=games.map(g=>{const ga=attempts.filter(a=>a.game===g.key);if(!ga.length)return `<div class="report-line"><strong>${g.name}</strong><span>${g.tier}</span><span>Not started</span><span>Attempts: 0</span></div>`;const accs=ga.map(remoteAccuracy);const best=Math.max(...accs);const latest=remoteAccuracy(ga[ga.length-1]);const avg=Math.round(accs.reduce((a,b)=>a+b,0)/accs.length);return `<div class="report-line"><strong>${g.name}</strong><span>${g.tier}</span><span>Best ${best}% | Latest ${latest}% | Avg ${avg}%</span><span>Attempts: ${ga.length}</span></div>`;}).join("");return `<div class="report-section"><div class="report-section-title">Learner</div><p>${name} · ${profile.department_role||"No role"}<br>Username: ${profile.username||"Not set"}</p></div><div class="report-grid"><div class="report-card"><span>Average</span><strong>${summary.completed?summary.avg+"%":"--"}</strong></div><div class="report-card"><span>Completed</span><strong>${summary.completed} / ${games.length}</strong></div><div class="report-card"><span>Status</span><strong>${summary.status}</strong></div></div><div class="report-section"><div class="report-section-title">Module Breakdown</div>${rows}</div><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:12px;"><button class="small-btn admin-reset-scores" data-id="${profile.id}">Reset Scores</button></div>`;}
async function loadAdminData(){const profile=loadProfile();if(!profile||!profile.isAdmin){adminOutput.textContent="Admin access required.";return;}if(!supabaseClient){adminOutput.textContent="Supabase is not connected.";return;}adminOutput.textContent="Loading admin data...";adminLearnerOutput.textContent="Loading learners...";const {data:orgs,error:orgErr}=await supabaseClient.from("organisations").select("id,name,licence_count,active,premium_enabled,billing_status,created_at").order("created_at",{ascending:false});const {data:profiles,error:profileErr}=await supabaseClient.from("profiles").select("id,username,first_name,surname,department_role,organisation,is_admin,premium_enabled,created_at").order("created_at",{ascending:false});const {data:attempts,error:attemptErr}=await supabaseClient.from("attempts").select("user_id,game,score,accuracy,correct_count,wrong_count,answered,duration_seconds,passed,created_at").order("created_at",{ascending:true});const {data:bills,error:billErr}=await supabaseClient.from("billing").select("id,organisation_id,amount,currency,status,invoice_reference,paypal_transaction_id,created_at").order("created_at",{ascending:false});if(orgErr||profileErr||attemptErr||billErr){adminOutput.textContent="Admin tables exist, but read policies are not fully enabled yet.";adminLearnerOutput.textContent="Learner reporting is blocked by policy. Check admin RLS policies.";billingOutput.textContent="Billing data blocked by policy until admin RLS is added.";return;}adminProfiles=profiles||[];adminAttempts=attempts||[];adminCompanyCount.textContent=(orgs||[]).length;adminLearnerCount.textContent=adminProfiles.filter(p=>!p.is_admin).length;adminLicenceCount.textContent=(orgs||[]).reduce((s,o)=>s+Number(o.licence_count||0),0);adminOutput.innerHTML=(orgs&&orgs.length)?orgs.map(o=>`<div class="report-line"><strong>${o.name}</strong><span>Licences: ${o.licence_count||0}</span><span>Billing: ${o.billing_status||"trial"}</span><span>Premium: ${o.premium_enabled?"Yes":"No"}</span></div>`).join(""):"No companies created yet.";adminLearnerOutput.innerHTML=adminProfiles.map(p=>{const learnerAttempts=adminAttempts.filter(a=>a.user_id===p.id);const s=buildRemoteSummary(learnerAttempts);const name=`${p.first_name||""} ${p.surname||""}`.trim()||p.username||"Learner";return `<div class="report-line"><strong>${name}</strong><span>${p.organisation||"SCCYBER"}</span><span>${s.completed}/${games.length} · ${s.status} · ${s.totalAttempts} attempts</span><span><button class="small-btn admin-view-report" data-id="${p.id}">View Report</button></span></div>`;}).join("")||"No learner profiles found.";billingOutput.innerHTML=(bills&&bills.length)?bills.map(b=>`<div class="report-line"><strong>${b.invoice_reference||"Invoice"}</strong><span>${b.currency||"GBP"} ${b.amount||0}</span><span>${b.status}</span><span>${b.paypal_transaction_id||"No PayPal ID"}</span></div>`).join(""):"No billing records yet.";}
function showAdminLearnerReport(userId){const p=adminProfiles.find(x=>x.id===userId);if(!p){adminSelectedReport.textContent="Learner not found.";return;}const attempts=adminAttempts.filter(a=>a.user_id===userId);adminSelectedReport.innerHTML=renderRemoteLearnerReport(p,attempts);}
async function resetLearnerScores(userId){if(!supabaseClient||!confirm("Reset this learner's scores? This will delete their attempt records."))return;const {error}=await supabaseClient.from("attempts").delete().eq("user_id",userId);if(error){adminSelectedReport.textContent="Reset failed. Check delete policy.";return;}if(loadProfile()?.supabaseUserId===userId){const p=loadProfile();p.attempts=[];p.scores={};saveProfile(p);updateDashboard();}await loadAdminData();adminSelectedReport.textContent="Scores reset. Select the learner again to view their updated report.";}
function openAdmin(){dashboardView.classList.add("hidden");reportView.classList.add("hidden");gameView.classList.add("hidden");adminView.classList.remove("hidden");loadAdminData();window.scrollTo(0,0);}
function closeAdmin(){adminView.classList.add("hidden");dashboardView.classList.remove("hidden");updateDashboard();window.scrollTo(0,0);}
function openReport(){const profile=loadProfile();if(!validProfile(profile)){alert("Enter your learner profile before viewing the report.");firstNameInput.focus();return;}updateDashboard();dashboardView.classList.add("hidden");gameView.classList.add("hidden");adminView.classList.add("hidden");reportView.classList.remove("hidden");window.scrollTo(0,0);}
function closeReport(){reportView.classList.add("hidden");dashboardView.classList.remove("hidden");updateDashboard();window.scrollTo(0,0);}
function openGame(title,url,gameKey){const profile=loadProfile();if(!validProfile(profile)){alert("Enter your first name, surname and department/role before starting a game.");firstNameInput.focus();return;}const game=games.find(g=>g.key===gameKey);if(game&&game.premium&&!hasPremiumAccess()){alert("This is a premium module. Upgrade to play.");return;}currentGameKey=gameKey;activeGameTitle.textContent=title;gameFrame.src=url;dashboardView.classList.add("hidden");reportView.classList.add("hidden");adminView.classList.add("hidden");gameView.classList.remove("hidden");window.scrollTo(0,0);}
function closeGame(){gameFrame.src="";currentGameKey=null;gameView.classList.add("hidden");dashboardView.classList.remove("hidden");updateDashboard();window.scrollTo(0,0);}
function requestAttemptAndClose(){try{gameFrame.contentWindow.postMessage({type:"SCCYBER_REQUEST_ATTEMPT"},"*");}catch(e){}setTimeout(closeGame,650);}
window.addEventListener("message",event=>{const data=event.data||{};if(data.type==="SCCYBER_GAME_ATTEMPT")addAttemptPayload(data);if(data.type==="SCCYBER_RETURN_TO_DASHBOARD")requestAttemptAndClose();});
credentialLoginBtn.addEventListener("click",credentialLogin);demoModeBtn.addEventListener("click",demoMode);logoutBtn.addEventListener("click",logout);loginBtn.addEventListener("click",()=>{const firstName=firstNameInput.value.trim(),surname=surnameInput.value.trim(),departmentRole=departmentRoleInput.value.trim();if(!firstName||!surname||!departmentRole){alert("Please enter first name, surname and department/role.");return;}saveProfile(createProfile(firstName,surname,departmentRole));updateDashboard();});
backBtn.addEventListener("click",requestAttemptAndClose);viewReportBtn.addEventListener("click",openReport);reportBackBtn.addEventListener("click",closeReport);adminBtn.addEventListener("click",openAdmin);adminBackBtn.addEventListener("click",closeAdmin);refreshAdminBtn.addEventListener("click",loadAdminData);adminView.addEventListener("click",e=>{const viewBtn=e.target.closest(".admin-view-report");if(viewBtn)showAdminLearnerReport(viewBtn.dataset.id);const resetBtn=e.target.closest(".admin-reset-scores");if(resetBtn)resetLearnerScores(resetBtn.dataset.id);});document.querySelectorAll(".play-btn").forEach(btn=>btn.addEventListener("click",()=>openGame(btn.dataset.title,btn.dataset.url,btn.closest(".game-card").dataset.game)));
initSupabase();