const games=[{key:"password-shield",name:"Password Shield",tier:"Easy",premium:false},{key:"workplace-defender",name:"Workplace Defender",tier:"Intermediate",premium:true},{key:"phishing-frenzy",name:"Phishing Frenzy",tier:"Easy",premium:true},{key:"breach-lockdown",name:"Breach Lockdown",tier:"Intermediate",premium:true},{key:"brute-force-lockdown",name:"Brute Force Lockdown",tier:"Advanced",premium:true}];
window.games=games;
const storageKey="sccyberPortalProfile",PASS_MARK=80;
let currentGameKey=null,currentGameOrigin=null,supabaseClient=null,adminProfiles=[],adminAttempts=[],adminOrgs=[];
const trustedGameOrigins=[location.origin,"https://sccyber.github.io"];
const $=id=>document.getElementById(id);
const authView=$("authView"),usernameInput=$("usernameInput"),passwordInput=$("passwordInput"),credentialLoginBtn=$("credentialLoginBtn"),demoModeBtn=$("demoModeBtn"),authMessage=$("authMessage");
const loginPanel=$("loginPanel"),learnerPanel=$("learnerPanel"),firstNameInput=$("firstName"),surnameInput=$("surname"),departmentRoleInput=$("departmentRole"),loginBtn=$("loginBtn"),learnerDisplay=$("learnerDisplay"),departmentDisplay=$("departmentDisplay"),logoutBtn=$("logoutBtn");
const overallScore=$("overallScore"),gamesCompleted=$("gamesCompleted"),trainingStatus=$("trainingStatus"),reportBadge=$("reportBadge"),reportProgress=$("reportProgress"),reportAttempts=$("reportAttempts"),reportOutput=$("reportOutput");
const dashboardView=$("dashboardView"),reportView=$("reportView"),viewReportBtn=$("viewReportBtn"),reportBackBtn=$("reportBackBtn"),gameView=$("gameView"),gameFrame=$("gameFrame"),activeGameTitle=$("activeGameTitle"),backBtn=$("backBtn");
const adminBtn=$("adminBtn"),adminView=$("adminView"),adminBackBtn=$("adminBackBtn"),refreshAdminBtn=$("refreshAdminBtn"),adminCompanyCount=$("adminCompanyCount"),adminLicenceCount=$("adminLicenceCount"),adminLearnerCount=$("adminLearnerCount"),adminOutput=$("adminOutput"),billingOutput=$("billingOutput"),adminLearnerOutput=$("adminLearnerOutput"),adminSelectedReport=$("adminSelectedReport");
const newCompanyName=$("newCompanyName"),newCompanyLicences=$("newCompanyLicences"),newCompanyPremium=$("newCompanyPremium"),newCompanyBilling=$("newCompanyBilling"),addCompanyBtn=$("addCompanyBtn"),companyMessage=$("companyMessage");
const newLearnerUsername=$("newLearnerUsername"),newLearnerFirstName=$("newLearnerFirstName"),newLearnerSurname=$("newLearnerSurname"),newLearnerRole=$("newLearnerRole"),newLearnerCompany=$("newLearnerCompany"),addLearnerBtn=$("addLearnerBtn"),learnerMessage=$("learnerMessage");
function loadProfile(){const p=JSON.parse(localStorage.getItem(storageKey)||"null");if(p&&!p.attempts)p.attempts=[];return p;}
function saveProfile(p){if(!p.attempts)p.attempts=[];localStorage.setItem(storageKey,JSON.stringify(p));}
function createProfile(firstName,surname,departmentRole){return{firstName:(firstName||"").trim(),surname:(surname||"").trim(),departmentRole:(departmentRole||"").trim(),name:`${(firstName||"").trim()} ${(surname||"").trim()}`.trim(),scores:{},attempts:[],createdAt:new Date().toISOString(),isAdmin:false,premiumEnabled:false,mode:"local"};}
function validProfile(p){return !!(p&&p.firstName&&p.surname&&p.departmentRole);}
function usernameToEmail(username){const clean=username.trim().toLowerCase();return clean.includes("@")?clean:`${clean}@sccyber.training`;}
function initSupabase(){const url=window.SCCYBER_SUPABASE_URL,key=window.SCCYBER_SUPABASE_ANON_KEY;if(!url||!key||url.includes("PASTE_")||key.includes("PASTE_")){authMessage.textContent="Supabase not connected yet. Use Demo Mode for local testing.";return;}supabaseClient=window.supabase.createClient(url,key);authMessage.textContent="Supabase ready. Enter learner credentials.";}
function showDashboard(){authView.classList.add("hidden");dashboardView.classList.remove("hidden");reportView.classList.add("hidden");gameView.classList.add("hidden");adminView.classList.add("hidden");updateDashboard();}
async function restoreSession(){const profile=loadProfile();if(validProfile(profile)){if(profile.mode==="demo"){showDashboard();return;}if(supabaseClient&&profile.mode==="live"){try{const {data}=await supabaseClient.auth.getSession();if(data.session){showDashboard();return;}}catch(e){}}showDashboard();}}
async function credentialLogin(){const username=usernameInput.value.trim(),password=passwordInput.value;if(!username||!password){authMessage.textContent="Enter username and password.";return;}if(!supabaseClient){authMessage.textContent="Supabase is not connected yet.";return;}authMessage.textContent="Checking credentials...";const {data,error}=await supabaseClient.auth.signInWithPassword({email:usernameToEmail(username),password});if(error){authMessage.textContent="Login failed. Check username and password.";return;}const user=data.user;const {data:pd}=await supabaseClient.from("profiles").select("first_name,surname,department_role,username,is_admin,premium_enabled,organisation").eq("id",user.id).single();let p;if(pd){p=createProfile(pd.first_name,pd.surname,pd.department_role);p.username=pd.username||username;p.isAdmin=!!pd.is_admin;p.premiumEnabled=!!pd.premium_enabled;p.organisation=pd.organisation||"";}else{p=createProfile(username,"Learner","Unassigned");p.username=username;}p.supabaseUserId=user.id;p.mode="live";saveProfile(p);showDashboard();}
function demoMode(){const p=createProfile("Demo","Learner","Demo");p.mode="demo";p.premiumEnabled=false;saveProfile(p);showDashboard();}
async function logout(){localStorage.removeItem(storageKey);try{if(supabaseClient)await supabaseClient.auth.signOut();}catch(e){}usernameInput.value="";passwordInput.value="";dashboardView.classList.add("hidden");reportView.classList.add("hidden");gameView.classList.add("hidden");adminView.classList.add("hidden");authView.classList.remove("hidden");authMessage.textContent="Logged out. Enter learner credentials.";window.scrollTo(0,0);}
function hasPremiumAccess(){const p=loadProfile();return !!(p&&p.premiumEnabled&&p.mode!=="demo");}
function attemptsFor(p,key){return(p.attempts||[]).filter(a=>a.game===key);}
function attemptAccuracy(a){if(a.accuracy!==null&&a.accuracy!==undefined&&!Number.isNaN(Number(a.accuracy)))return Number(a.accuracy);if(a.answered&&a.correct!==null&&a.correct!==undefined)return Math.round(Number(a.correct)/Number(a.answered)*100);return 0;}
function bestAccuracy(a){return a.length?Math.max(...a.map(attemptAccuracy)):0;}
function latestAccuracy(a){return a.length?attemptAccuracy(a[a.length-1]):0;}
function averageAccuracy(a){return a.length?Math.round(a.reduce((s,x)=>s+attemptAccuracy(x),0)/a.length):0;}
function bestScore(a){return a.length?Math.max(...a.map(x=>Number(x.score||0))):0;}
function trainingGrade(avg,done){if(done<games.length)return"IN PROGRESS";return avg>=PASS_MARK?"PASS":"FAIL";}
function calculateSummary(p){const completedGames=games.filter(g=>attemptsFor(p,g.key).length>0),done=completedGames.length,bests=completedGames.map(g=>bestAccuracy(attemptsFor(p,g.key))),avg=done?Math.round(bests.reduce((a,b)=>a+b,0)/done):0;return{completed:done,avg,totalAttempts:(p.attempts||[]).length,status:done?trainingGrade(avg,done):"START TRAINING"};}
async function saveAttemptToSupabase(a){const p=loadProfile();if(!supabaseClient||!p?.supabaseUserId||p.mode==="demo")return;await supabaseClient.from("attempts").insert({user_id:p.supabaseUserId,game:a.game,score:a.score,accuracy:a.accuracy,correct_count:a.correct,wrong_count:a.wrong,answered:a.answered,duration_seconds:a.durationSeconds,passed:a.passed,created_at:a.createdAt});}
function addAttemptPayload(data){let p=loadProfile();if(!validProfile(p))return;const game=data.game||currentGameKey,score=Number(data.score||0);if(!game)return;const a={firstName:p.firstName,surname:p.surname,learnerName:p.name,departmentRole:p.departmentRole,game,score,source:data.source||"game",totalQuestions:data.totalQuestions||null,correct:data.correct||null,wrong:data.wrong||null,answered:data.answered||null,accuracy:data.accuracy||null,durationSeconds:data.durationSeconds||null,completed:data.completed!==false,passed:data.passed||false,role:data.role||null,threatsStopped:data.threatsStopped||null,biggestWeakness:data.biggestWeakness||null,createdAt:data.createdAt||new Date().toISOString()};const dupe=p.attempts.some(x=>x.game===a.game&&x.score===a.score&&x.answered===a.answered&&Math.abs(new Date(x.createdAt).getTime()-new Date(a.createdAt).getTime())<1500);if(dupe)return;p.attempts.push(a);p.scores[game]=bestScore(attemptsFor(p,game));saveProfile(p);saveAttemptToSupabase(a);updateDashboard();}
function updateReport(p,s){if(!validProfile(p)){reportBadge.textContent="AWAITING PROFILE";reportProgress.textContent=`0 / ${games.length}`;reportAttempts.textContent="0";reportOutput.textContent="Enter learner details to start generating report data.";return;}reportProgress.textContent=`${s.completed} / ${games.length}`;reportAttempts.textContent=s.totalAttempts;reportBadge.textContent=s.status;if(s.totalAttempts===0){reportOutput.innerHTML="Complete at least one module to generate report data.";return;}const lines=games.map(g=>{const a=attemptsFor(p,g.key);if(!a.length)return `<div class="report-line"><strong>${g.name}</strong><span>${g.tier}</span><span>${g.premium&&!hasPremiumAccess()?"Premium locked":"Not started"}</span><span>Attempts: 0</span></div>`;return `<div class="report-line"><strong>${g.name}</strong><span>${g.tier}</span><span>Best ${bestAccuracy(a)}% | Latest ${latestAccuracy(a)}% | Avg ${averageAccuracy(a)}%</span><span>Attempts: ${a.length}</span></div>`;}).join("");reportOutput.innerHTML=`<div class="report-section"><div class="report-section-title">Learner</div><p>${p.name} · ${p.departmentRole}</p></div><div class="report-section"><div class="report-section-title">Module Breakdown</div>${lines}</div>`;}
function updatePremiumButtons(){const premium=hasPremiumAccess();document.querySelectorAll(".game-card[data-premium='true']").forEach(card=>{const btn=card.querySelector(".play-btn"),score=card.querySelector(".game-score");if(premium){btn.textContent="Play";if(score.textContent==="Premium access required")score.textContent="No score yet";}else{btn.textContent="Upgrade to Play";score.textContent="Premium access required";}});}
function updateDashboard(){const p=loadProfile();if(!validProfile(p)){loginPanel.classList.remove("hidden");learnerPanel.classList.add("hidden");adminBtn.classList.add("hidden");overallScore.textContent="--";gamesCompleted.textContent=`0 / ${games.length}`;trainingStatus.textContent="ENTER PROFILE";games.forEach(g=>{const el=$("score-"+g.key);if(el)el.textContent=g.premium?"Premium access required":"Profile required";});updatePremiumButtons();updateReport(p,{completed:0,avg:0,totalAttempts:0,status:"ENTER PROFILE"});return;}loginPanel.classList.add("hidden");learnerPanel.classList.remove("hidden");learnerDisplay.textContent=p.name;departmentDisplay.textContent=p.departmentRole;p.isAdmin?adminBtn.classList.remove("hidden"):adminBtn.classList.add("hidden");const s=calculateSummary(p);overallScore.textContent=s.completed?`${s.avg}%`:"--";gamesCompleted.textContent=`${s.completed} / ${games.length}`;trainingStatus.textContent=s.completed?s.status:"START TRAINING";games.forEach(g=>{const el=$("score-"+g.key),a=attemptsFor(p,g.key);if(!el)return;if(g.premium&&!hasPremiumAccess()){el.textContent="Premium access required";return;}if(!a.length){el.textContent="No attempts yet";return;}el.innerHTML=`Best: ${bestAccuracy(a)}%<br>Latest: ${latestAccuracy(a)}%<br>Attempts: ${a.length}<br>Average: ${averageAccuracy(a)}%`;});updatePremiumButtons();updateReport(p,s);}
function remoteAccuracy(a){if(a.accuracy!==null&&a.accuracy!==undefined&&!Number.isNaN(Number(a.accuracy)))return Number(a.accuracy);if(a.answered&&a.correct_count!==null&&a.correct_count!==undefined)return Math.round(Number(a.correct_count)/Number(a.answered)*100);return 0;}
function buildRemoteSummary(attempts){const completed=games.filter(g=>attempts.some(a=>a.game===g.key));const done=completed.length,bests=completed.map(g=>Math.max(...attempts.filter(a=>a.game===g.key).map(remoteAccuracy))),avg=done?Math.round(bests.reduce((a,b)=>a+b,0)/done):0;return{completed:done,avg,status:done<games.length?"IN PROGRESS":avg>=PASS_MARK?"PASS":"FAIL",totalAttempts:attempts.length};}
function renderRemoteLearnerReport(p,attempts){const s=buildRemoteSummary(attempts),name=`${p.first_name||""} ${p.surname||""}`.trim()||p.username||"Learner";const rows=games.map(g=>{const ga=attempts.filter(a=>a.game===g.key);if(!ga.length)return `<div class="report-line"><strong>${g.name}</strong><span>${g.tier}</span><span>Not started</span><span>Attempts: 0</span></div>`;const accs=ga.map(remoteAccuracy),best=Math.max(...accs),latest=remoteAccuracy(ga[ga.length-1]),avg=Math.round(accs.reduce((a,b)=>a+b,0)/accs.length);return `<div class="report-line"><strong>${g.name}</strong><span>${g.tier}</span><span>Best ${best}% | Latest ${latest}% | Avg ${avg}%</span><span>Attempts: ${ga.length}</span></div>`;}).join("");return `<div class="report-section"><div class="report-section-title">Learner</div><p>${name} · ${p.department_role||"No role"}<br>Username: ${p.username||"Not set"}</p></div><div class="report-grid"><div class="report-card"><span>Average</span><strong>${s.completed?s.avg+"%":"--"}</strong></div><div class="report-card"><span>Completed</span><strong>${s.completed} / ${games.length}</strong></div><div class="report-card"><span>Status</span><strong>${s.status}</strong></div></div><div class="report-section"><div class="report-section-title">Module Breakdown</div>${rows}</div><button class="small-btn admin-reset-scores" data-id="${p.id}">Reset Scores</button>`;}
function populateCompanySelect(){if(newLearnerCompany)newLearnerCompany.innerHTML='<option value="">Select company</option>'+adminOrgs.map(o=>`<option value="${o.id}">${o.name}</option>`).join("");}
async function addCompany(){const p=loadProfile();if(!p?.isAdmin||!supabaseClient)return;const name=newCompanyName.value.trim();if(!name){companyMessage.textContent="Enter a company name.";return;}const {error}=await supabaseClient.from("organisations").insert({name,licence_count:Number(newCompanyLicences.value||0),premium_enabled:newCompanyPremium.value==="true",billing_status:newCompanyBilling.value||"trial"});companyMessage.textContent=error?"Could not add company. Check policy or duplicate name.":"Company added.";if(!error){newCompanyName.value="";newCompanyLicences.value="";await loadAdminData();}}
async function updateCompany(id){const row=document.querySelector(`[data-org-row="${id}"]`);if(!row)return;const {error}=await supabaseClient.from("organisations").update({licence_count:Number(row.querySelector(".org-licences").value||0),premium_enabled:row.querySelector(".org-premium").value==="true",billing_status:row.querySelector(".org-billing").value}).eq("id",id);if(error){adminOutput.textContent="Update failed. Check admin update policy.";return;}await loadAdminData();}
async function addLearnerRecord(){const username=newLearnerUsername.value.trim().toLowerCase();if(!username){learnerMessage.textContent="Enter a username.";return;}const {error}=await supabaseClient.from("learners").insert({username,organisation_id:newLearnerCompany.value||null,active:true});learnerMessage.textContent=error?"Could not add learner record. Check policy or duplicate username.":`Learner record added. Suggested login email: ${usernameToEmail(username)}`;if(!error){newLearnerUsername.value="";newLearnerFirstName.value="";newLearnerSurname.value="";newLearnerRole.value="";await loadAdminData();}}
async function removeLearnerRecord(id,username){if(!confirm(`Remove learner record for ${username}? This removes them from the company/licence list.`))return;const {error}=await supabaseClient.from("learners").delete().eq("id",id);if(error){adminLearnerOutput.textContent="Could not remove learner. Check delete policy.";return;}await loadAdminData();}
async function loadAdminData(){const p=loadProfile();if(!p?.isAdmin||!supabaseClient)return;const orgs=await supabaseClient.from("organisations").select("*").order("created_at",{ascending:false});adminOrgs=orgs.data||[];populateCompanySelect();const profiles=await supabaseClient.from("profiles").select("id,first_name,surname,department_role,username,organisation,is_admin,premium_enabled,created_at").order("created_at",{ascending:false});adminProfiles=profiles.data||[];const learners=await supabaseClient.from("learners").select("id,username,organisation_id,user_id,active,created_at").order("created_at",{ascending:false});const learnerRows=learners.data||[];const attempts=await supabaseClient.from("attempts").select("*").order("created_at",{ascending:true});adminAttempts=attempts.data||[];const billing=await supabaseClient.from("billing_events").select("*").order("created_at",{ascending:false}).limit(20);renderAdmin(learnerRows,billing.data||[]);}
function renderAdmin(learnerRows,billingRows){adminCompanyCount.textContent=adminOrgs.length;adminLicenceCount.textContent=adminOrgs.reduce((s,o)=>s+Number(o.licence_count||0),0);adminLearnerCount.textContent=learnerRows.length;adminOutput.innerHTML=adminOrgs.map(o=>`<div class="report-line" data-org-row="${o.id}"><strong>${o.name}</strong><span><input class="org-licences" type="number" value="${o.licence_count||0}"></span><span><select class="org-premium"><option value="false" ${!o.premium_enabled?"selected":""}>Premium off</option><option value="true" ${o.premium_enabled?"selected":""}>Premium on</option></select><select class="org-billing"><option ${o.billing_status==="trial"?"selected":""}>trial</option><option ${o.billing_status==="pending"?"selected":""}>pending</option><option ${o.billing_status==="paid"?"selected":""}>paid</option><option ${o.billing_status==="overdue"?"selected":""}>overdue</option></select></span><span><button class="small-btn admin-update-org" data-id="${o.id}">Save</button></span></div>`).join("")||"No companies yet.";adminLearnerOutput.innerHTML=learnerRows.map(l=>{const prof=adminProfiles.find(p=>p.id===l.user_id)||{},org=adminOrgs.find(o=>o.id===l.organisation_id),uid=l.user_id||"";return `<div class="report-line"><strong>${l.username}</strong><span>${org?org.name:"No company"}</span><span>${uid?"Login active":"No login yet"}${prof.premium_enabled?" · Premium":""}</span><span>${uid?`<button class="small-btn admin-report" data-id="${uid}">View Report</button> `:""}<button class="small-btn admin-remove-learner" data-id="${l.id}" data-username="${l.username}">Remove</button></span></div>`;}).join("")||"No learners yet.";billingOutput.innerHTML=billingRows.map(b=>`<div class="report-line"><strong>${b.event_type}</strong><span>${b.amount||""} ${b.currency||""}</span><span>${b.status||""}</span><span>${new Date(b.created_at).toLocaleDateString()}</span></div>`).join("")||"No billing events yet.";}
function showAdminLearnerReport(id){const p=adminProfiles.find(x=>x.id===id);if(!p){adminSelectedReport.textContent="Learner not found.";return;}adminSelectedReport.innerHTML=renderRemoteLearnerReport(p,adminAttempts.filter(a=>a.user_id===id));}
async function resetLearnerScores(id){if(!confirm("Reset all scores for this learner?"))return;const {error}=await supabaseClient.from("attempts").delete().eq("user_id",id);if(error){adminSelectedReport.textContent="Could not reset scores. Check delete policy.";return;}await loadAdminData();showAdminLearnerReport(id);}
function openAdmin(){dashboardView.classList.add("hidden");adminView.classList.remove("hidden");loadAdminData();}
function openReport(){dashboardView.classList.add("hidden");reportView.classList.remove("hidden");updateDashboard();}
function resolveGameOrigin(url){try{return new URL(url,location.href).origin}catch(e){return null}}
function trustedGameMessage(e){return e.source===gameFrame.contentWindow&&currentGameOrigin&&e.origin===currentGameOrigin&&trustedGameOrigins.includes(e.origin);}
function openGame(title,url,key){if(!validProfile(loadProfile())){alert("Enter learner details first.");return;}const origin=resolveGameOrigin(url);if(!origin||!trustedGameOrigins.includes(origin)){alert("This game source is not trusted. Please contact SCCYBER.");return;}currentGameKey=key;currentGameOrigin=origin;activeGameTitle.textContent=title;gameFrame.src=url;dashboardView.classList.add("hidden");gameView.classList.remove("hidden");window.scrollTo(0,0);}
function closeGame(){gameFrame.src="";currentGameKey=null;currentGameOrigin=null;gameView.classList.add("hidden");dashboardView.classList.remove("hidden");updateDashboard();}
function requestAttemptAndClose(){try{gameFrame.contentWindow.postMessage({type:"SCCYBER_REQUEST_ATTEMPT"},currentGameOrigin||location.origin);}catch(e){}setTimeout(closeGame,650);}
window.addEventListener("message",e=>{if(!trustedGameMessage(e))return;const d=e.data||{};if(d.type==="SCCYBER_GAME_ATTEMPT")addAttemptPayload(d);if(d.type==="SCCYBER_RETURN_TO_DASHBOARD")requestAttemptAndClose();});
credentialLoginBtn.addEventListener("click",credentialLogin);demoModeBtn.addEventListener("click",demoMode);logoutBtn.addEventListener("click",logout);loginBtn.addEventListener("click",()=>{const p=createProfile(firstNameInput.value,surnameInput.value,departmentRoleInput.value);saveProfile(p);showDashboard();});viewReportBtn.addEventListener("click",openReport);reportBackBtn.addEventListener("click",()=>{reportView.classList.add("hidden");dashboardView.classList.remove("hidden");});backBtn.addEventListener("click",requestAttemptAndClose);adminBtn.addEventListener("click",openAdmin);adminBackBtn.addEventListener("click",()=>{adminView.classList.add("hidden");dashboardView.classList.remove("hidden");});refreshAdminBtn.addEventListener("click",loadAdminData);addCompanyBtn.addEventListener("click",addCompany);addLearnerBtn.addEventListener("click",addLearnerRecord);adminView.addEventListener("click",e=>{const t=e.target;if(t.classList.contains("admin-update-org"))updateCompany(t.dataset.id);if(t.classList.contains("admin-report"))showAdminLearnerReport(t.dataset.id);if(t.classList.contains("admin-reset-scores"))resetLearnerScores(t.dataset.id);if(t.classList.contains("admin-remove-learner"))removeLearnerRecord(t.dataset.id,t.dataset.username);});document.querySelectorAll(".play-btn").forEach(btn=>btn.addEventListener("click",()=>openGame(btn.dataset.title,btn.dataset.url,btn.closest(".game-card").dataset.game)));initSupabase();restoreSession();
